# Generated by Django 5.1 on 2024-09-21 03:41

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Codigo Produto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Produto')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to='produtos', variations={'thumb': (125, 125)}, verbose_name='Imagem')),
            ],
        ),
    ]
