# Generated by Django 5.1 on 2024-10-30 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produtos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('data_nascimento', models.DateField(verbose_name='Data deNascimento')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.IntegerField(max_length=20, verbose_name='Telefone')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo',
            field=models.IntegerField(auto_created=True, blank=True, primary_key=True, serialize=False, unique=True, verbose_name='Código Produto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_produto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.produtos'),
        ),
    ]
