# Generated by Django 5.1 on 2024-10-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_delete_produto_alter_produtos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
