# Generated by Django 5.1 on 2024-10-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.BigIntegerField(verbose_name='Telefone'),
        ),
    ]
